GET http://localhost:3030

###

GET http://localhost:3030/messages/


###

DELETE http://localhost:3030/messages/

###

POST http://localhost:3030/messages
Content-Type: application/json

{
    "from": "Jerione",
    "text": "I am not here today"
}

###

GET http://localhost:3030/messages/search?text=welcome
